layout: default
title: COBE Lab Equipment Documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark
logo: "/assets/images/Logo_Cognition_neg_UK.png"

url: https://just-the-docs.github.io

aux_links: